Squashed 'vendor/ansible/' changes from b9e9302..5691a77
5691a77 Merge pull request #211 from mapuri/contivctl
522290b use recent contivctl released script
22b36af Merge pull request #210 from mapuri/ucp
ef419e6 cleanup volplugin socket file once the service stops
1d6c546 cleanup netplugin socket file once the service stops
0a6db33 etcd setup enhancements - remove Requires attribute from etcd unit   - this ensures that systemd tries to restart etcd     even when docker service is manually restarted. - set RestartSec for etcd service to prevent too fast restarts - exit early on service start if docker is not running - remove an un-needed exit from etcd stop script
81312f0 remove the fifo file as part of ucp service stop
ca0f1b6 Merge pull request #209 from mapuri/netctl
11530b2 temporarily use netctl for setting aci mode
429a6e5 Merge pull request #203 from mapuri/etcd
ea12c7f add make file targets for common testing tasks
3f626e8 run etcd inside a container
14f0f95 Merge pull request #202 from mapuri/ucp
172ffc2 use the id command to get ucp instance-id
f2c0f5c Merge pull request #200 from mapuri/ucarp
502f40e don't copy clusterm conf file if it exists

git-subtree-dir: vendor/ansible
git-subtree-split: 5691a776ea2241bc20fc9037196b68e8bf5ee7d1

diff --git a/roles/etcd/templates/etcd.j2 b/roles/etcd/templates/etcd.j2
--- a/roles/etcd/templates/etcd.j2
+++ b/roles/etcd/templates/etcd.j2
@@ -15,7 +15,7 @@ http://{{ addr }}:{{ etcd_client_port1 }},http://{{ addr }}:{{ etcd_client_port2
 {%- macro get_peer_addr() -%}
     {# we can't use a simple filter as shown, as it needs python 2.8.
      # So resorting to loop below to get a peer.
-    {%- set peer_name=groups[etcd_peers_group]|reject("equalto", node_name)|first -%} #}
+     #{%- set peer_name=groups[etcd_peers_group]|reject("equalto", node_name)|first -%} #}
     {%- set peers=[] -%}
     {%- for host in groups[etcd_peers_group] -%}
         {%- if host != node_name -%}
@@ -124,6 +124,15 @@ export ETCD_ELECTION_TIMEOUT={{ etcd_election_timeout }}
 set -x
 case $1 in
 start)
+    # check if docker is running, else fail early.
+    # this is done instead of adding a 'Requires' dependency for docker in
+    # unit file to ensure that the etcd service starts as soon as docker starts
+    # even after a manual restart of docker.
+    out=$(/usr/bin/docker ps 2>&1 | grep -o "Cannot connect to the Docker daemon")
+    if [ "${out}" == "Cannot connect to the Docker daemon" ]; then
+        echo "docker is not running."
+        exit 1
+    fi
     {% if run_as == "worker" -%}
     {{ add_proxy() }}
     {% elif etcd_init_cluster -%}
@@ -135,7 +144,20 @@ start)
 
     #start etcd
     echo "==> starting etcd with environment:" `env`
-    /usr/bin/etcd
+    /usr/bin/docker run -t --rm --net=host --name etcd \
+        -e ETCD_NAME=${ETCD_NAME} \
+        -e ETCD_DATA_DIR=${ETCD_DATA_DIR} \
+        -e ETCD_INITIAL_CLUSTER_TOKEN=${ETCD_INITIAL_CLUSTER_TOKEN} \
+        -e ETCD_LISTEN_CLIENT_URLS=${ETCD_LISTEN_CLIENT_URLS} \
+        -e ETCD_ADVERTISE_CLIENT_URLS=${ETCD_ADVERTISE_CLIENT_URLS} \
+        -e ETCD_INITIAL_ADVERTISE_PEER_URLS=${ETCD_INITIAL_ADVERTISE_PEER_URLS} \
+        -e ETCD_LISTEN_PEER_URLS=${ETCD_LISTEN_PEER_URLS} \
+        -e ETCD_HEARTBEAT_INTERVAL=${ETCD_HEARTBEAT_INTERVAL} \
+        -e ETCD_ELECTION_TIMEOUT=${ETCD_ELECTION_TIMEOUT} \
+        -e ETCD_INITIAL_CLUSTER=${ETCD_INITIAL_CLUSTER} \
+        -e ETCD_INITIAL_CLUSTER_STATE=${ETCD_INITIAL_CLUSTER_STATE} \
+        -e ETCD_PROXY=${ETCD_PROXY} \
+        quay.io/coreos/etcd:{{ etcd_version }}
     ;;
 
 stop)
@@ -145,18 +167,15 @@ stop)
         {% set peer_addr=get_peer_addr() -%}
         {% if peer_addr == "" -%}
         echo "==> no peer found or single member cluster at time of commission"
-        exit 1
         {% else -%}
         {{ remove_member(peer_addr=peer_addr) }}
         {% endif %}
     {% else -%}
     {{ remove_member(peer_addr=etcd_master_addr) }}
     {% endif -%}
-    ;;
 
-post-stop)
-    #XXX: is there a case when we should not cleanup the data dir on stop?
-    rm -rf $ETCD_DATA_DIR
+    /usr/bin/docker stop etcd
+    /usr/bin/docker rm etcd
     ;;
 
 *)
